[package]
name = "hsm"
version = "0.1.0"
authors = ["wizkr <wizkr@example.com>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
bitcoin = { version = "0.27", default-features = false, features = ["no-std", "use-serde", "secp-lowmemory"] }
